const TYPE = {
	COUNTER_INCREMENT: 'COUNTER/INCREMENT',
	COUNTER_DECREMENT: 'COUNTER/DECREMENT',

	USERNAME_TRACK_TYPING: 'USERNAME/TRACK_TYPING',

	START_WARS_PERSONAGE_REQUEST_DATA: 'START_WARS_PERSONAGE/REQUEST_DATA' 
}

export default TYPE
