const TYPE = {
	COUNTER_INCREMENT: 'COUNTER/INCREMENT',
	COUNTER_DECREMENT: 'COUNTER/DECREMENT',

	USERNAME_TRACK_TYPING: 'USERNAME/TRACK_TYPING',
	USERNAME_LOST_FOCUS: 'USERNAME/LOST_FOCUS'
}

export default TYPE
